apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uuy014ao4-nodejs
  janus-idp.io/tekton: uuy014ao4-nodejs
  backstage.io/kubernetes-id: uuy014ao4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uuy014ao4-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
