apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uuy014ao4-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uuy014ao4-nodejs 
  name: uuy014ao4-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uuy014ao4-nodejs 
